#!/bin/bash
command="$1"
host="$2"
env_token="TF_TOKEN_${host//./_}"

if [ "$command" = "get" ]; then
  if  [ -z "${!env_token}" ]; then
    echo "{}"
  else
    echo "{ \"token\": \"${!env_token}\" }"
  fi
  exit 0
else
  exit 1
fi
